### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by wangzonghui1994** [oisc/ChineseDiscourseParser#1]
请问，出现了以下错误，是怎么回事呢
![image](https://user-images.githubusercontent.com/44188475/80476597-2dc4a200-897d-11ea-8f56-870473edc245.png)

**Comment by oisc** [comment]
Berkeley Parser 没有输出结果，util/berkeley.py 实现比较简单，建议检查下你的当前环境用命令行调用 berkeley parser 有没有问题，参考 https://github.com/slavpetrov/berkeleyparser
