### ISSUE TITLE
超时问题

### ISSUE THREAD

**Issue by wangzonghui1994** [oisc/ChineseDiscourseParser#2]
你好，在运行长文档，长句子时，好像出现了你说的那个超时问题，请问您解决这个问题了吗。

**Comment by oisc** [comment]
在生成成分句法树时使用到了 Berkeley Parser, 然而 Berkeley Parser 在 parsing 长句子时非常耗时，因此我在训练和验证时生成了一份缓存的成分句法树。你可以尝试使用其他基于 CTB 6.0 的成分句法分析器替换 Berkeley Parser，或者尝试将 util/berkeley 的 timeout 设置更长超时时间。

**Comment by wangzonghui1994** [comment]
您好，很抱歉再次打扰你，因为当前我的需求，在我的实验中是快速获得文章的Edus，用这些Edus继续其他工作，而篇章分析倒不是十分需求，请问，针对您的模型，在什么地方可以修改呢，或者有什么建议，再或者什么方式能快速得到文章的Edus，十分感谢！！！

**Comment by oisc** [comment]
我在 segmenter 下实现了两种 EDU 分割方法，一种是基于句法树特征 + SVM 的 `segmenter.svm`， 一种是基于依存句法 + GCN + tagging 的方法的 `segmenter.gcn`。后一种方法的依存句法使用 thulac 生成，速度比较快，但 part of speech 我还是使用了 berkeley parser 的成分句法树的 POS，你可以尝试使用等价的 POS tagger（如果使用我发布的训练好的模型，请确保 POS 和 Berkeley Parser 的 POS 一致）。
更建议您参考我师弟的一篇文章 "葛海柱, 孔芳. 基于多任务学习的汉语基本篇章单元和主述位联合识别[J]. 中文信息学报, 2020, 34(1): 71-79."
